import {
  AlertTriangle,
  ArrowRight,
  Baby,
  Ban,
  Bath,
  BedDouble,
  BellRing,
  Bike,
  Bird,
  Blinds,
  BookOpen,
  Building,
  Building2,
  Car,
  Cat,
  Check,
  ChevronLeft,
  ChevronRight,
  Cigarette,
  CigaretteOff,
  CircleX,
  CircuitBoardIcon,
  ClipboardCheck,
  Clock,
  // Additional lucide-react icons for amenities
  Coffee,
  Command,
  CreditCard,
  CreditCardIcon,
  File,
  FileText,
  Gamepad2,
  HelpCircle,
  Hotel,
  Image,
  ImageIcon,
  LandPlot,
  Laptop,
  Laptop2,
  LayoutDashboardIcon,
  Library,
  ListOrdered,
  Loader2,
  LogIn,
  type LucideIcon,
  LucideShoppingBag,
  Luggage,
  MapPinHouse,
  MessageCircleQuestion,
  Microwave,
  Moon,
  MoreVertical,
  Mountain,
  Palette,
  Phone,
  Pizza,
  Plane,
  Plus,
  Printer,
  Settings,
  ShieldCheck,
  ShowerHead,
  Sofa,
  Store,
  Sun,
  SunMedium,
  Ticket,
  Trash,
  Tv,
  Twitter,
  Umbrella,
  UserCircle2Icon,
  UserPen,
  Users,
  UserX2Icon,
  UtensilsCrossed,
  VolumeX,
  Wifi,
  Wrench,
  X,
} from "lucide-react-native";

// Import necessary react-icons
import {
  MdAccessible,
  MdAcUnit,
  MdBalcony,
  MdBeachAccess,
  MdCelebration,
  MdChildCare,
  MdDeck,
  MdElevator,
  MdFitnessCenter,
  MdHotTub,
  MdKitchen,
  MdLocalBar,
  MdLocalLaundryService,
  MdLocationCity,
  MdLogout,
  MdMovie,
  MdOutlineCleaningServices,
  MdRestaurantMenu,
  MdRoom,
  MdSecurity,
  MdSpa,
  MdSportsEsports,
  MdStars,
  MdSupportAgent,
  MdWaterDrop,
  MdWeekend,
} from "react-icons/md";

import {
  FaCar,
  FaConciergeBell,
  FaGolfBall,
  FaSpa,
  FaTableTennis,
} from "react-icons/fa";
import { PiHairDryer } from "react-icons/pi";

export type Icon = LucideIcon | React.ComponentType;

export const Icons = {
  "message-circlec-question": MessageCircleQuestion,
  dashboard: LayoutDashboardIcon,
  logo: Command,
  login: LogIn,
  close: X,
  product: LucideShoppingBag,
  spinner: Loader2,
  kanban: CircuitBoardIcon,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  employee: UserX2Icon,
  post: FileText,
  page: File,
  userPen: UserPen,
  user2: UserCircle2Icon,
  media: Image,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  warning: AlertTriangle,
  users: Users,
  arrowRight: ArrowRight,
  help: HelpCircle,
  pizza: Pizza,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  twitter: Twitter,
  check: Check,
  ticket: Ticket,
  creditCard: CreditCardIcon,
  listOrdered: ListOrdered,
  palette: Palette,
  image: ImageIcon,
  "message-circle-question": MessageCircleQuestion,
  building: Building2,
  bath: Bath,
  shower: ShowerHead,
  hotel: Hotel,
  mapPinHouse: MapPinHouse,
  wifi: Wifi,
  clock: Clock,
  cancel: CircleX,
  ban: Ban,
  "no-smoking": CigaretteOff,
  smoking: Cigarette,
  "clipboard-check": ClipboardCheck,

  // Amenity-specific icons
  ac_unit: MdAcUnit,
  accessible: MdAccessible,
  alarm: Clock,
  atm: CreditCardIcon,
  airport_shuttle: Plane,
  beach_access: MdBeachAccess,
  bedroom: BedDouble,
  bedroom_parent: BedDouble,
  business_center: Building,
  chair: Sofa,
  child_care: MdChildCare,
  child_friendly: Baby,
  cleaning_services: MdOutlineCleaningServices,
  computer: Laptop2,
  coffee: Coffee,
  concierge: FaConciergeBell,
  curtains: Blinds,
  currency_exchange: CreditCardIcon,
  desk: Laptop2,
  directions_car: Car,
  // dry: Wind,
  deck: MdDeck,
  elevator: MdElevator,
  ev_station: Car,
  fitness_center: MdFitnessCenter,
  flight: Plane,
  golf_course: FaGolfBall,
  hot_tub: MdHotTub,
  hvac: MdAcUnit,
  iron: Wrench,
  kitchen: MdKitchen,
  landscape: Mountain,
  local_bar: MdLocalBar,
  local_laundry_service: MdLocalLaundryService,
  location_city: MdLocationCity,
  lock: ShieldCheck,
  // login: MdLogin,
  logout: MdLogout,
  luggage: Luggage,
  microwave: Microwave,
  movie: MdMovie,
  menu_book: BookOpen,
  newspaper: FileText,
  outdoor_grill: UtensilsCrossed,
  park: LandPlot,
  pedal_bike: Bike,
  pets: Cat,
  phone: Phone,
  print: Printer,
  restaurant: UtensilsCrossed,
  restaurant_menu: MdRestaurantMenu,
  room_service: BellRing,
  sauna: MdHotTub,
  security: MdSecurity,
  self_improvement: MdSpa,
  smart_display: Tv,
  smoke_free: CigaretteOff,
  smoking_rooms: Cigarette,
  sports_esports: MdSportsEsports,
  sports_tennis: FaTableTennis,
  stars: MdStars,
  store: Store,
  support_agent: MdSupportAgent,
  tour: MapPinHouse,
  tv: Tv,
  umbrella: Umbrella,
  volume_off: VolumeX,
  water: MdWaterDrop,
  wb_sunny: Sun,
  weekend: MdWeekend,
  yard: Bird,
  balcony: MdBalcony,
  celebration: MdCelebration,
  "game-room": Gamepad2,
  "beach-bar": MdLocalBar,
  "pool-bar": MdLocalBar,
  spa: FaSpa,
  car_rental: FaCar,
  "airport-transfer": Plane,
  "butler-service": MdRoom,
  local_library: Library,
  dry: PiHairDryer,
} as const;
